"""
Django settings for dailyfresh project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# import sys
# sys.path.append(os.path.join(BASE_DIR,'apps'))  # 将apps目录添加到python的包搜索路径

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r!*l(!^69n(&fm=d53m7ii40e%)%k9s1__$omky459!!tl77uw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'haystack',  # 全文检索引擎
    'tinymce',  # 符文本编辑器
    'apps.cart',  # 购物车模块
    'apps.user',  # 用户模块
    'apps.goods',  # 商品模块
    'apps.order',  # 订单模块
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'dailyfresh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],  # 设置模板目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dailyfresh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # 使用mysql数据库
        'NAME': 'dailyfresh', # 数据库名
        'HOST': '127.0.0.1',  # 数据库主机ip
        'PORT': 3306,  # 数据库主机端口号
        'USER': 'root',  # 数据库登陆用户名
        'PASSWORD': 'mysql',  # 数据量登陆密码
    }
}

AUTH_USER_MODEL = 'user.User'  # 指定django认证系统使用的用户模型类

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'  # 设置中文

TIME_ZONE = 'Asia/Shanghai'  # 设置时区

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# 收集静态文件根目录
STATIC_ROOT = '/var/www/dailyfresh/static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')] # 配置静态文件夹的物理路径

# The setting of tinymce editor
TINYMCE_DEFAULT_CONFIG = {
    'theme': 'advanced',
    'width': 600,
    'height': 400,
}

# 发送邮件配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 邮件发送服务器
EMAIL_HOST = 'smtp.aliyun.com'
EMAIL_PORT = 25
# 发送邮件的邮箱
EMAIL_HOST_USER = 'jdy879526487@aliyun.com'
# 在邮箱中设置的客户端授权密码
EMAIL_HOST_PASSWORD = 'ws13429830518'
# 收件人看到的发件人
EMAIL_FROM = 'dailyfresh<jdy879526487@aliyun.com>'



# 设置Django框架的缓存
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # 设置django缓存的数据保存在redis数据库中
        "LOCATION": "redis://127.0.0.1:6379/5",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Django的session存储设置
SESSION_ENGINE = "django.contrib.sessions.backends.cache"

# 设置session信息存储在CACHES配置项default对应的redis中
SESSION_CACHE_ALIAS = "default"

# 配置login_required 在验证不通过时候跳转的路径
LOGIN_URL = '/user/login'

# 设置文件上传使用的Storage子类
DEFAULT_FILE_STORAGE = 'utils.fdfs.storage.FDFStorage'

# Nginx服务器的路径和端口号
NGINX_URL = 'http://192.168.227.128:8888/'

# 配置FDFS客户端配置文件路径
FDFS_CLIENT_CONF = 'utils.fdfs.client.conf'


# 全文检索框架的配置
HAYSTACK_CONNECTIONS = {
    'default' : {
        #  使用whoosh引擎
        #  'EGINE' : 'haystack.backends.whoosh_backend.Whoosh_Engine',
         'EGINE' : 'haystack.backends.whoosh_cn_backend.Whoosh_Engine',
        # 索引文件路径
        'PATH' : os.path.join(BASE_DIR, 'whoosh_index'),
    }
}

# 当添加,修改,删除数据时，自动生成索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

# 阿里pay的SDK需要的参数
ALIPAY_SETTING = {
    'appid' : "2016091200491955",  # 应用APPID
    'app_notify_url' : None,  # 默认回调url
    'app_private_key_path' : os.path.join(BASE_DIR,'apps/order/app_private_key.pem'),  # 应用私钥文件路径# 支付宝的公钥文件，验证支付宝回传消息使用，不是你自己的公钥,
    'alipay_public_key_path' : os.path.join(BASE_DIR,'apps/order/app_public_key.pem'),
    'sign_type' : "RSA2",  # RSA 或者 RSA2
    'debug' : True  # 默认False，False代表线上环境，True代表沙箱环境
}

# 支付界面url
ALIPAY_URL = 'https://openapi.alipaydev.com/gateway.do?'
# 订单标题
ALIPAY_TITLE = '测试订单'
# 订单返回结果url
ALIPAY_RETURN_URL = "http://192.168.227.128:8000/order/pay"




